version: "3.7"
# STACK FOR KUMA

########################### NETWORKS
# Define as EXTERNAL

networks:
  t2_proxy:
    external: true
  
########################### SERVICES
services:
  ############################# KUMA

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: unless-stopped
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/data/kuma:/app/data
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.uptimekuma-rtr.entrypoints=https"
      - "traefik.http.routers.uptimekuma-rtr.rule=Host(`uptime.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.uptimekuma-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.uptimekuma-rtr.service=uptimekuma-svc"
      - "traefik.http.services.uptimekuma-svc.loadbalancer.server.port=3001"
      ## HTTP Routers Local
      - "traefik.http.routers.uptimekuma-rtr-local.entrypoints=https"
      - "traefik.http.routers.uptimekuma-rtr-local.rule=Host(`uptimekuma.$LOCALDOMAIN`)"
      - "traefik.http.routers.uptimekuma-rtr-local.tls=true"
      - "traefik.http.routers.uptimekuma-rtr-local.service=uptimekuma-svc-local"
      - "traefik.http.services.uptimekuma-svc-local.loadbalancer.server.port=3001"